/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form.Login;

import Koneksi.koneksi;
import Utils.Common;
import Utils.ModelUser;
import java.io.UnsupportedEncodingException;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.misc.BASE64Encoder;

/**
 *
 * @author Baladika
 */
public class Login extends javax.swing.JFrame {
            String username;
        String password,u,p,ep,changep;

    /**
     * Creates new form login
     */
    public Login()  {
        initComponents();
        
        //menghilangkan icon ceklis dan silang
        user_ceklis.setVisible(false);
        user_silang.setVisible(false);
        pass_ceklis.setVisible(false);
        pass_silang.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbStaff = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        rbStruk = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        btnMasuk = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        user_ceklis = new javax.swing.JLabel();
        pass_silang = new javax.swing.JLabel();
        user_silang = new javax.swing.JLabel();
        pass_ceklis = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnSetting = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 100, 127));

        buttonGroup1.add(rbStaff);
        rbStaff.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbStaff.setForeground(new java.awt.Color(255, 255, 255));
        rbStaff.setSelected(true);
        rbStaff.setText("  STAFF");
        jPanel3.add(rbStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 127));

        buttonGroup1.add(rbStruk);
        rbStruk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbStruk.setForeground(new java.awt.Color(255, 255, 255));
        rbStruk.setText("STRUKTUR");
        jPanel3.add(rbStruk, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, -1, -1));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 260, 10));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PASSWORD");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));

        user.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 140, -1));

        btnKembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnKembali.setText("KEMBALI");
        jPanel3.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 120, 40));

        btnMasuk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMasuk.setText("MASUK");
        btnMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasukActionPerformed(evt);
            }
        });
        jPanel3.add(btnMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 120, 40));

        pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 140, -1));
        jPanel3.add(user_ceklis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 30, 20));
        jPanel3.add(pass_silang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 30, 20));
        jPanel3.add(user_silang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 30, 20));
        jPanel3.add(pass_ceklis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 30, 20));

        jToolBar1.setRollover(true);

        btnSetting.setFocusable(false);
        btnSetting.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSetting.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSetting);

        jPanel3.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 60, 30));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 510));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 510));

        setSize(new java.awt.Dimension(418, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasukActionPerformed
        // TODO add your handling code here:
  
        u = user.getText();
        p = pass.getText();
        
        try{
            ep = ""+encrypt(p, "SHA-1", "UTF-16").toString();
            
        }       catch (Exception ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
        
        searchUser(u, ep);
        
        System.out.println(ep);
        
        if(!u.equalsIgnoreCase(username)){
            JOptionPane.showMessageDialog(null, "Tidak bisa login, cek username dan password anda");
        }else{
            if (u.equals(username)) {
                System.out.println(username);
            }
            
            if (ep.equals(password)) {
                System.out.println("Normal pass " + p);
                System.out.println("Encrypted pass " + password);
                ModelUser user = new ModelUser();
                user.setUser(u);
                user.setPassword(password);
                user.setRole(1);
                Common.currentUser = user;
//                Common.currentUser.setUser(u);
//                Common.currentUser.setPassword(password);
//                Common.currentUser.setRole(1);
                
                tambah_struk ts = new tambah_struk();
                ts.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Password salah");
            }
            
        }
        
//        if (rbStaff.isSelected()) {
//            String username = "staff";
//            String password = "123";
//            //kondisi 1, dimana jika form user dan pass kosong
//            if(user.getText().equals("") || pass.getText().equals("")) {
//                JOptionPane.showMessageDialog(null, "Username atau Password tidak boleh kosong!", "ERROR", JOptionPane.WARNING_MESSAGE);
//                user.setText("");
//                pass.setText("");
//                user.requestFocus();
//                user_silang.setVisible(true);
//                pass_silang.setVisible(true);
//            }
//            //kondisi 2, dimana user dan pass benar
//            else if (username.equalsIgnoreCase(user.getText()) && password.equalsIgnoreCase(pass.getText()) ){
//                JOptionPane.showMessageDialog(null, "Login berhasil", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
//                
//            }
//            //kondisi 3, dimana username benar, tetapi pass salah
//            else if (username.equalsIgnoreCase(user.getText())) {
//                JOptionPane.showMessageDialog(null, "Password anda salah, mohon di cek kembali", "ERROR", JOptionPane.WARNING_MESSAGE);
//                user_ceklis.setVisible(true);
//                user_silang.setVisible(false);
//                pass_silang.setVisible(true);
//                pass_silang.setVisible(true);
//                pass.setText("");
//                pass.requestFocus();
//                
//            }
//            //kondisi 4, dimana username salah
//            else{
//                JOptionPane.showMessageDialog(null, "Username anda salah, Anda bukan seorang STAFF!", "ERROR", JOptionPane.WARNING_MESSAGE);
//                user_silang.setVisible(true);
//                user_ceklis.setVisible(false);
//                user.setText("");
//                pass.setText("");
//                user.requestFocus();
//            }
//     
//        }
//        else{
//            String username = "aslab";
//            String password = "321";
//            if(user.getText().equals("") || pass.getText().equals("")) {
//                JOptionPane.showMessageDialog(null, "Username atau Password tidak boleh kosong!", "ERROR", JOptionPane.WARNING_MESSAGE);
//                user.setText("");
//                pass.setText("");
//                user.requestFocus();
//                user_silang.setVisible(true);
//                pass_silang.setVisible(true);
//            }
//            else if (username.equalsIgnoreCase(user.getText()) && password.equalsIgnoreCase(pass.getText()) ){
//                JOptionPane.showMessageDialog(null, "Login berhasil", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
//                
//            }else if (username.equalsIgnoreCase(user.getText())) {
//                JOptionPane.showMessageDialog(null, "Password anda salah, mohon di cek kembali", "ERROR", JOptionPane.WARNING_MESSAGE);
//                user_ceklis.setVisible(true);
//                user_silang.setVisible(false);
//                pass_silang.setVisible(true);
//                pass_silang.setVisible(true);
//                pass.setText("");
//                pass.requestFocus();
//                
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "Username anda salah, Anda bukan seorang ASLAB!", "ERROR", JOptionPane.WARNING_MESSAGE);
//                user_silang.setVisible(true);
//                user_ceklis.setVisible(false);
//                user.setText("");
//                pass.setText("");
//                user.requestFocus();
//            }
//            
//        }
        
    }//GEN-LAST:event_btnMasukActionPerformed

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        login_setting lgset = new login_setting();
        lgset.setVisible(true);
    }//GEN-LAST:event_btnSettingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnMasuk;
    private javax.swing.JButton btnSetting;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPasswordField pass;
    private javax.swing.JLabel pass_ceklis;
    private javax.swing.JLabel pass_silang;
    private javax.swing.JRadioButton rbStaff;
    private javax.swing.JRadioButton rbStruk;
    private javax.swing.JTextField user;
    private javax.swing.JLabel user_ceklis;
    private javax.swing.JLabel user_silang;
    // End of variables declaration//GEN-END:variables


    public void searchUser(String user,String pass){

        try{
        //set koneksi
        Connection connection = koneksi.getConnection();
        ResultSet rs;
        Statement statement = connection.createStatement();
        
        String sql = "select * from user where username='"+user+"' and password='"+pass+"'";
        
        rs = statement.executeQuery(sql);
        
            if (rs.next()) {
                username = rs.getString(1);
                password = rs.getString(2);
                
            }
            
//            connection.close();
        
            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public static synchronized String encrypt(String plaintext,String algorithm, String encoding) throws Exception{
        MessageDigest msgDigest = null;
        String hashValue = null;
        
        try{
            msgDigest = MessageDigest.getInstance(algorithm);
            msgDigest.update(plaintext.getBytes(encoding));
            byte rawByte[]  = msgDigest.digest();
            hashValue  = (new BASE64Encoder()).encode(rawByte);
            
        }catch(NoSuchAlgorithmException e){
            System.out.println("No such algorithm");
        }
        catch(UnsupportedEncodingException e){
            System.out.println("The encoding is not supported");
        }
        
        return hashValue;
                
    }
    
}
