/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.StrukturOrganisasi;

import Image.SetImage;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.Popup;
import javax.swing.UIManager;

/**
 *
 * @author Fahtul Rahman
 */
public class StrukturOrganisasi extends javax.swing.JFrame {

    /**
     * Creates new form StrukturOrganisasi
     */
    public StrukturOrganisasi() {
        initComponents();
         this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpDasar = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        popUpMenengah = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        popUpLanjut = new javax.swing.JPopupMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelBackground = new javax.swing.JPanel();
        jPanel3 = new SetImage("backroundpanel.jpg");
        panelUtama = new javax.swing.JPanel();
        labelUtama = new javax.swing.JLabel();
        panelLanjut = new javax.swing.JPanel();
        labelLanjut = new javax.swing.JLabel();
        panelMenengah = new javax.swing.JPanel();
        labelMenengah = new javax.swing.JLabel();
        panelDasar = new javax.swing.JPanel();
        labelDasar = new javax.swing.JLabel();
        panelAll = new javax.swing.JPanel();
        labelAll = new javax.swing.JLabel();

        popUpDasar.setBackground(new java.awt.Color(0, 51, 51));
        popUpDasar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        jMenuItem1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/023-teamwork-1.png"))); // NOI18N
        jMenuItem1.setLabel("Depok");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popUpDasar.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jMenuItem2.setLabel("Kalimalang");
        popUpDasar.add(jMenuItem2);

        jMenuItem3.setLabel("Karawaci");
        popUpDasar.add(jMenuItem3);

        jMenuItem5.setLabel("Depok");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        popUpMenengah.add(jMenuItem5);

        jMenuItem6.setLabel("Kalimalang");
        popUpMenengah.add(jMenuItem6);

        jMenuItem7.setLabel("Karawaci");
        popUpMenengah.add(jMenuItem7);

        jMenuItem8.setLabel("Depok");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        popUpLanjut.add(jMenuItem8);

        jMenuItem9.setLabel("Kalimalang");
        popUpLanjut.add(jMenuItem9);

        jMenuItem10.setLabel("Karawaci");
        popUpLanjut.add(jMenuItem10);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(73, 5, 130));

        jLabel1.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PILIH LABORATORIUM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        panelBackground.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 924, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1464, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(108, 92, 231));

        panelUtama.setBackground(new java.awt.Color(73, 5, 130));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUtamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUtamaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelUtamaMouseReleased(evt);
            }
        });

        labelUtama.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelUtama.setForeground(new java.awt.Color(255, 255, 255));
        labelUtama.setText("Utama");
        labelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUtamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUtamaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUtama)
                .addGap(122, 122, 122))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUtama)
                .addContainerGap())
        );

        panelLanjut.setBackground(new java.awt.Color(73, 5, 130));
        panelLanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLanjutMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelLanjutMouseReleased(evt);
            }
        });

        labelLanjut.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelLanjut.setForeground(new java.awt.Color(255, 255, 255));
        labelLanjut.setText("Laboratorium Lanjut");
        labelLanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLanjutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLanjutLayout = new javax.swing.GroupLayout(panelLanjut);
        panelLanjut.setLayout(panelLanjutLayout);
        panelLanjutLayout.setHorizontalGroup(
            panelLanjutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanjutLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(labelLanjut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLanjutLayout.setVerticalGroup(
            panelLanjutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanjutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLanjut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenengah.setBackground(new java.awt.Color(73, 5, 130));
        panelMenengah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenengahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenengahMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMenengahMouseReleased(evt);
            }
        });

        labelMenengah.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelMenengah.setForeground(new java.awt.Color(255, 255, 255));
        labelMenengah.setText("Laboratorium Menengah");
        labelMenengah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMenengahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMenengahMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenengahLayout = new javax.swing.GroupLayout(panelMenengah);
        panelMenengah.setLayout(panelMenengahLayout);
        panelMenengahLayout.setHorizontalGroup(
            panelMenengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenengahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMenengah)
                .addGap(98, 98, 98))
        );
        panelMenengahLayout.setVerticalGroup(
            panelMenengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenengahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMenengah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDasar.setBackground(new java.awt.Color(73, 5, 130));
        panelDasar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDasarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDasarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDasarMouseReleased(evt);
            }
        });

        labelDasar.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelDasar.setForeground(new java.awt.Color(255, 255, 255));
        labelDasar.setText("Laboratorium Dasar");
        labelDasar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDasarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDasarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelDasarLayout = new javax.swing.GroupLayout(panelDasar);
        panelDasar.setLayout(panelDasarLayout);
        panelDasarLayout.setHorizontalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelDasar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDasarLayout.setVerticalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDasarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDasar)
                .addContainerGap())
        );

        panelAll.setBackground(new java.awt.Color(73, 5, 130));
        panelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAllMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelAllMouseReleased(evt);
            }
        });

        labelAll.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelAll.setForeground(new java.awt.Color(255, 255, 255));
        labelAll.setText("All");
        labelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAllMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAllLayout = new javax.swing.GroupLayout(panelAll);
        panelAll.setLayout(panelAllLayout);
        panelAllLayout.setHorizontalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAllLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(labelAll)
                .addGap(143, 143, 143))
        );
        panelAllLayout.setVerticalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAllLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelAll)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMenengah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLanjut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(panelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMenengah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelDasarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDasarMouseEntered
        panelDasar.setBackground(UIManager.getColor("control"));
         if(!evt.isPopupTrigger()){
          popUpDasar.show(this, 350,250);
     }
    }//GEN-LAST:event_labelDasarMouseEntered

    private void labelDasarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDasarMouseExited
        panelDasar.setBackground(new Color(73, 5, 130));
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_labelDasarMouseExited

    private void panelDasarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDasarMouseEntered
        panelDasar.setBackground(UIManager.getColor("control"));
     
     if(!evt.isPopupTrigger()){
          popUpDasar.show(this, 350,250);
     }
     
     popUpMenengah.setVisible(false);
     popUpLanjut.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDasarMouseEntered

    private void panelDasarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDasarMouseExited
        panelDasar.setBackground(new Color(73, 5, 130));
     
    }//GEN-LAST:event_panelDasarMouseExited

    private void panelDasarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDasarMouseReleased
      
    }//GEN-LAST:event_panelDasarMouseReleased

    private void labelMenengahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenengahMouseEntered
        // TODO add your handling code here:
         panelMenengah.setBackground(UIManager.getColor("control"));
         if(!evt.isPopupTrigger()){
          popUpMenengah.show(this, 350,320);
     }
    }//GEN-LAST:event_labelMenengahMouseEntered

    private void labelMenengahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenengahMouseExited
                       panelMenengah.setBackground(new Color(73, 5, 130));
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMenengahMouseExited

    private void panelMenengahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenengahMouseEntered
    panelMenengah.setBackground(UIManager.getColor("control"));
        if(!evt.isPopupTrigger()){
          popUpMenengah.show(this, 350,320);
     }
     
     popUpDasar.setVisible(false);
     popUpLanjut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenengahMouseEntered

    private void panelMenengahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenengahMouseExited
        // TODO add your handling code here:
           panelMenengah.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_panelMenengahMouseExited

    private void panelMenengahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenengahMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenengahMouseReleased

    private void labelLanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLanjutMouseEntered
        // TODO add your handling code here:
        panelLanjut.setBackground(UIManager.getColor("control"));
         if(!evt.isPopupTrigger()){
          popUpLanjut.show(this, 350,390);
     }
    }//GEN-LAST:event_labelLanjutMouseEntered

    private void labelLanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLanjutMouseExited
        // TODO add your handling code here:
        panelLanjut.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_labelLanjutMouseExited

    private void panelLanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLanjutMouseEntered
        // TODO add your handling code here:
        panelLanjut.setBackground(UIManager.getColor("control"));
         if(!evt.isPopupTrigger()){
          popUpLanjut.show(this, 350,390);}
    }//GEN-LAST:event_panelLanjutMouseEntered

    private void panelLanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLanjutMouseExited
        // TODO add your handling code here:
        panelLanjut.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_panelLanjutMouseExited

    private void panelLanjutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLanjutMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelLanjutMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void labelUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtamaMouseEntered
      panelUtama.setBackground(UIManager.getColor("control"));
      popUpDasar.setVisible(false);
      popUpMenengah.setVisible(false);
      popUpLanjut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_labelUtamaMouseEntered

    private void labelUtamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtamaMouseExited
    panelUtama.setBackground(new Color(73, 5, 130));
    // TODO add your handling code here:
    }//GEN-LAST:event_labelUtamaMouseExited

    private void panelUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseEntered
      panelUtama.setBackground(UIManager.getColor("control"));
      popUpDasar.setVisible(false);
      popUpMenengah.setVisible(false);
      popUpLanjut.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtamaMouseEntered

    private void panelUtamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseExited
    panelUtama.setBackground(new Color(73, 5, 130));        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtamaMouseExited

    private void panelUtamaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtamaMouseReleased

    private void labelAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAllMouseEntered
      panelAll.setBackground(UIManager.getColor("control"));
      popUpDasar.setVisible(false);
      popUpMenengah.setVisible(false);
      popUpLanjut.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_labelAllMouseEntered

    private void labelAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAllMouseExited
    panelAll.setBackground(new Color(73, 5, 130));        // TODO add your handling code here:
    }//GEN-LAST:event_labelAllMouseExited

    private void panelAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseEntered
      panelAll.setBackground(UIManager.getColor("control"));
      popUpDasar.setVisible(false);
      popUpMenengah.setVisible(false);
      popUpLanjut.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_panelAllMouseEntered

    private void panelAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseExited
    panelAll.setBackground(new Color(73, 5, 130));
 // TODO add your handling code here:
    }//GEN-LAST:event_panelAllMouseExited

    private void panelAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAllMouseReleased

    private void panelAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseClicked
          All all = new All();
          all.setVisible(true);
    }//GEN-LAST:event_panelAllMouseClicked

    private void labelAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAllMouseClicked
        All all = new All();
         
          all.setVisible(true);
    }//GEN-LAST:event_labelAllMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StrukturOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StrukturOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StrukturOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StrukturOrganisasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StrukturOrganisasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAll;
    private javax.swing.JLabel labelDasar;
    private javax.swing.JLabel labelLanjut;
    private javax.swing.JLabel labelMenengah;
    private javax.swing.JLabel labelUtama;
    private javax.swing.JPanel panelAll;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelDasar;
    private javax.swing.JPanel panelLanjut;
    private javax.swing.JPanel panelMenengah;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPopupMenu popUpDasar;
    private javax.swing.JPopupMenu popUpLanjut;
    private javax.swing.JPopupMenu popUpMenengah;
    // End of variables declaration//GEN-END:variables
}
