/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.JobDesk;

import Image.SetImage;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Fahtul Rahman
 */
public class JobDeskHome extends javax.swing.JFrame {

    /**
     * Creates new form JobDeskHome
     */
    public JobDeskHome() {
        initComponents();
               this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        strukturasisten = new javax.swing.JPopupMenu();
        koordinator = new javax.swing.JMenuItem();
        sekretaris = new javax.swing.JMenuItem();
        bendahara = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new SetImage("backroundpanel.jpg");
        panelUtama = new javax.swing.JPanel();
        labelUtama = new javax.swing.JLabel();
        panelLanjut = new javax.swing.JPanel();
        labelLanjut = new javax.swing.JLabel();
        panelMenengah = new javax.swing.JPanel();
        labelMenengah = new javax.swing.JLabel();
        panelDasar = new javax.swing.JPanel();
        labelDasar = new javax.swing.JLabel();
        panelAll = new javax.swing.JPanel();
        labelAll = new javax.swing.JLabel();
        panelUtama1 = new javax.swing.JPanel();
        labelUtama1 = new javax.swing.JLabel();
        panelUtama2 = new javax.swing.JPanel();
        labelUtama2 = new javax.swing.JLabel();
        panelBackground = new javax.swing.JPanel();

        koordinator.setText("Koordinator");
        strukturasisten.add(koordinator);

        sekretaris.setText("Sekretaris");
        strukturasisten.add(sekretaris);

        bendahara.setText("Bendahara");
        strukturasisten.add(bendahara);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(73, 5, 130));

        jLabel1.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PILIH LABORATORIUM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(437, 437, 437)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(108, 92, 231));

        panelUtama.setBackground(new java.awt.Color(73, 5, 130));
        panelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUtamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUtamaMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelUtamaMouseReleased(evt);
            }
        });

        labelUtama.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelUtama.setForeground(new java.awt.Color(255, 255, 255));
        labelUtama.setText("Struktur Asisten");
        labelUtama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUtamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUtamaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUtama)
                .addGap(122, 122, 122))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUtama)
                .addContainerGap())
        );

        panelLanjut.setBackground(new java.awt.Color(73, 5, 130));
        panelLanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelLanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelLanjutMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelLanjutMouseReleased(evt);
            }
        });

        labelLanjut.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelLanjut.setForeground(new java.awt.Color(255, 255, 255));
        labelLanjut.setText("Staff Maintenence");
        labelLanjut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLanjutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLanjutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLanjutLayout = new javax.swing.GroupLayout(panelLanjut);
        panelLanjut.setLayout(panelLanjutLayout);
        panelLanjutLayout.setHorizontalGroup(
            panelLanjutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLanjutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelLanjut)
                .addGap(101, 101, 101))
        );
        panelLanjutLayout.setVerticalGroup(
            panelLanjutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLanjutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLanjut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        panelMenengah.setBackground(new java.awt.Color(73, 5, 130));
        panelMenengah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelMenengahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelMenengahMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelMenengahMouseReleased(evt);
            }
        });

        labelMenengah.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelMenengah.setForeground(new java.awt.Color(255, 255, 255));
        labelMenengah.setText("Staff Administrasi");
        labelMenengah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelMenengahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelMenengahMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelMenengahLayout = new javax.swing.GroupLayout(panelMenengah);
        panelMenengah.setLayout(panelMenengahLayout);
        panelMenengahLayout.setHorizontalGroup(
            panelMenengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenengahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMenengah)
                .addGap(98, 98, 98))
        );
        panelMenengahLayout.setVerticalGroup(
            panelMenengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenengahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMenengah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelDasar.setBackground(new java.awt.Color(73, 5, 130));
        panelDasar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelDasarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelDasarMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelDasarMouseReleased(evt);
            }
        });

        labelDasar.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelDasar.setForeground(new java.awt.Color(255, 255, 255));
        labelDasar.setText("Staff Dasar, Menengah, Lanjut ");
        labelDasar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDasarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDasarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelDasarLayout = new javax.swing.GroupLayout(panelDasar);
        panelDasar.setLayout(panelDasarLayout);
        panelDasarLayout.setHorizontalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDasarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(labelDasar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDasarLayout.setVerticalGroup(
            panelDasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDasarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDasar)
                .addContainerGap())
        );

        panelAll.setBackground(new java.awt.Color(73, 5, 130));
        panelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAllMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelAllMouseReleased(evt);
            }
        });

        labelAll.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelAll.setForeground(new java.awt.Color(255, 255, 255));
        labelAll.setText("Koordinator Laboratorium");
        labelAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelAllMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelAllLayout = new javax.swing.GroupLayout(panelAll);
        panelAll.setLayout(panelAllLayout);
        panelAllLayout.setHorizontalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(labelAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAllLayout.setVerticalGroup(
            panelAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAllLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAll)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUtama1.setBackground(new java.awt.Color(73, 5, 130));
        panelUtama1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUtama1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUtama1MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelUtama1MouseReleased(evt);
            }
        });

        labelUtama1.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelUtama1.setForeground(new java.awt.Color(255, 255, 255));
        labelUtama1.setText("Asisten Laboratorium");
        labelUtama1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUtama1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUtama1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUtama1Layout = new javax.swing.GroupLayout(panelUtama1);
        panelUtama1.setLayout(panelUtama1Layout);
        panelUtama1Layout.setHorizontalGroup(
            panelUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtama1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUtama1)
                .addGap(76, 76, 76))
        );
        panelUtama1Layout.setVerticalGroup(
            panelUtama1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtama1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUtama1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelUtama2.setBackground(new java.awt.Color(73, 5, 130));
        panelUtama2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelUtama2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelUtama2MouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                panelUtama2MouseReleased(evt);
            }
        });

        labelUtama2.setFont(new java.awt.Font("Arno Pro Smbd", 1, 30)); // NOI18N
        labelUtama2.setForeground(new java.awt.Color(255, 255, 255));
        labelUtama2.setText("Programmer");
        labelUtama2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelUtama2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelUtama2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelUtama2Layout = new javax.swing.GroupLayout(panelUtama2);
        panelUtama2.setLayout(panelUtama2Layout);
        panelUtama2Layout.setHorizontalGroup(
            panelUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUtama2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelUtama2)
                .addGap(132, 132, 132))
        );
        panelUtama2Layout.setVerticalGroup(
            panelUtama2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtama2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelUtama2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelDasar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelLanjut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelMenengah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(panelUtama1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelUtama2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(panelAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDasar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelMenengah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLanjut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelUtama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelUtama2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        panelBackground.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 553, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtamaMouseEntered
        panelUtama.setBackground(UIManager.getColor("control"));
     
    }//GEN-LAST:event_labelUtamaMouseEntered

    private void labelUtamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtamaMouseExited
        panelUtama.setBackground(new Color(73, 5, 130));
        // TODO add your handling code here:
    }//GEN-LAST:event_labelUtamaMouseExited

    private void panelUtamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseEntered
        panelUtama.setBackground(UIManager.getColor("control"));
     if(!evt.isPopupTrigger()){
          strukturasisten.show(this, 430,470);
     }

        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtamaMouseEntered

    private void panelUtamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseExited
        panelUtama.setBackground(new Color(73, 5, 130));        // TODO add your handling code here:
     
    }//GEN-LAST:event_panelUtamaMouseExited

    private void panelUtamaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtamaMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtamaMouseReleased

    private void labelLanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLanjutMouseEntered
        // TODO add your handling code here:
        panelLanjut.setBackground(UIManager.getColor("control"));
        if(!evt.isPopupTrigger()){

        }
    }//GEN-LAST:event_labelLanjutMouseEntered

    private void labelLanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLanjutMouseExited
        // TODO add your handling code here:
        panelLanjut.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_labelLanjutMouseExited

    private void panelLanjutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLanjutMouseEntered
        // TODO add your handling code here:
        panelLanjut.setBackground(UIManager.getColor("control"));
        if(!evt.isPopupTrigger()){
        }
           strukturasisten.setVisible(false);
    }//GEN-LAST:event_panelLanjutMouseEntered

    private void panelLanjutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLanjutMouseExited
        // TODO add your handling code here:
        panelLanjut.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_panelLanjutMouseExited

    private void panelLanjutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLanjutMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelLanjutMouseReleased

    private void labelMenengahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenengahMouseEntered
        // TODO add your handling code here:
        panelMenengah.setBackground(UIManager.getColor("control"));
        
    }//GEN-LAST:event_labelMenengahMouseEntered

    private void labelMenengahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelMenengahMouseExited
        panelMenengah.setBackground(new Color(73, 5, 130));
        // TODO add your handling code here:
    }//GEN-LAST:event_labelMenengahMouseExited

    private void panelMenengahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenengahMouseEntered
        panelMenengah.setBackground(UIManager.getColor("control"));
   strukturasisten.setVisible(false);        
        
    }//GEN-LAST:event_panelMenengahMouseEntered

    private void panelMenengahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenengahMouseExited
        // TODO add your handling code here:
        panelMenengah.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_panelMenengahMouseExited

    private void panelMenengahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenengahMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenengahMouseReleased

    private void labelDasarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDasarMouseEntered
        panelDasar.setBackground(UIManager.getColor("control"));
        if(!evt.isPopupTrigger()){
        
        }
    }//GEN-LAST:event_labelDasarMouseEntered

    private void labelDasarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDasarMouseExited
        panelDasar.setBackground(new Color(73, 5, 130));

        // TODO add your handling code here:
    }//GEN-LAST:event_labelDasarMouseExited

    private void panelDasarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDasarMouseEntered
        panelDasar.setBackground(UIManager.getColor("control"));
   strukturasisten.setVisible(false);
        if(!evt.isPopupTrigger()){
        
        }

        
        // TODO add your handling code here:
    }//GEN-LAST:event_panelDasarMouseEntered

    private void panelDasarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDasarMouseExited
        panelDasar.setBackground(new Color(73, 5, 130));

        // TODO add your handling code here:
    }//GEN-LAST:event_panelDasarMouseExited

    private void panelDasarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelDasarMouseReleased

    }//GEN-LAST:event_panelDasarMouseReleased

    private void labelAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAllMouseEntered
        panelAll.setBackground(UIManager.getColor("control"));
        
    }//GEN-LAST:event_labelAllMouseEntered

    private void labelAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAllMouseExited
        panelAll.setBackground(new Color(73, 5, 130));        // TODO add your handling code here:
    }//GEN-LAST:event_labelAllMouseExited

    private void panelAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseEntered
   strukturasisten.setVisible(false);
   panelAll.setBackground(UIManager.getColor("control"));
        
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAllMouseEntered

    private void panelAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseExited
        panelAll.setBackground(new Color(73, 5, 130));
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAllMouseExited

    private void panelAllMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAllMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelAllMouseReleased

    private void labelUtama1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtama1MouseEntered
  panelUtama1.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_labelUtama1MouseEntered

    private void labelUtama1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtama1MouseExited
panelUtama1.setBackground(new Color(73, 5, 130));
        // TODO add your handling code here:
    }//GEN-LAST:event_labelUtama1MouseExited

    private void panelUtama1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtama1MouseEntered
        panelUtama1.setBackground(UIManager.getColor("control"));
           strukturasisten.setVisible(false);
    }//GEN-LAST:event_panelUtama1MouseEntered

    private void panelUtama1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtama1MouseExited
       panelUtama1.setBackground(new Color(73, 5, 130));
    }//GEN-LAST:event_panelUtama1MouseExited

    private void panelUtama1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtama1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtama1MouseReleased

    private void labelUtama2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtama2MouseEntered
    panelUtama2.setBackground(UIManager.getColor("control"));
    }//GEN-LAST:event_labelUtama2MouseEntered

    private void labelUtama2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUtama2MouseExited
panelUtama2.setBackground(new Color(73, 5, 130));        // TODO add your handling code here:
    }//GEN-LAST:event_labelUtama2MouseExited

    private void panelUtama2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtama2MouseEntered
  panelUtama2.setBackground(UIManager.getColor("control"));
     strukturasisten.setVisible(false);
    }//GEN-LAST:event_panelUtama2MouseEntered

    private void panelUtama2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtama2MouseExited
panelUtama2.setBackground(new Color(73, 5, 130));        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtama2MouseExited

    private void panelUtama2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelUtama2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_panelUtama2MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobDeskHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobDeskHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem bendahara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem koordinator;
    private javax.swing.JLabel labelAll;
    private javax.swing.JLabel labelDasar;
    private javax.swing.JLabel labelLanjut;
    private javax.swing.JLabel labelMenengah;
    private javax.swing.JLabel labelUtama;
    private javax.swing.JLabel labelUtama1;
    private javax.swing.JLabel labelUtama2;
    private javax.swing.JPanel panelAll;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelDasar;
    private javax.swing.JPanel panelLanjut;
    private javax.swing.JPanel panelMenengah;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JPanel panelUtama1;
    private javax.swing.JPanel panelUtama2;
    private javax.swing.JMenuItem sekretaris;
    private javax.swing.JPopupMenu strukturasisten;
    // End of variables declaration//GEN-END:variables
}
